import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MySideBar from "./components/SideBar/MySideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BMR • Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="hidden md:flex">{children}</div>
        <div className=" md:hidden h-screen w-full flex justify-center items-center">
          MobileSupport soon :3 (about me)
        </div>
      </body>
    </html>
  );
}
