import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MySideBar from "./components/SideBar/MySideBar";
import { Suspense } from "react";
import MyLoading from "./MyLoading";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BMR • Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="hidden md:block">
          <Suspense fallback={<MyLoading />}>
            <div className="relative z-20">
              <MySideBar />
            </div>
            <div className="ml-[20%]">
              {children}
              <SpeedInsights />
            </div>
          </Suspense>
        </div>
        <div className=" md:hidden h-screen w-full flex justify-center items-center">
          MobileSupport soon :3 (about me)
        </div>
      </body>
    </html>
  );
}
